### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by rffontenelle**
To ignore files from configure and build processes

### CODE REVIEW

**Comment by jpwhiting** [comment]
git.mk should already handle .gitignore creation, no?

**Comment by rffontenelle** [comment]
If it should, I'm not sure how it works.  I ran `./build.sh` and './configure' and untracked files popped up. The only `.gitignore` I see in the code are already git-tracked in

```
./doc/.gitignore
./src/server/.gitignore
./src/tests/.gitignore
./src/clients/say/.gitignore
./src/clients/spdsend/.gitignore
./po/.gitignore
```

**Comment by jpwhiting** [comment]
make -f git.mk

 should add anything missing to the Makefile.am

**Comment by Nardol** [comment]
Git.mk is processed during make, not during configure.

**Comment by rffontenelle** [comment]
Thanks for clarification. I tested locally and I can see what you mean.

FWIW, the following files still show up as untracker after make. Should they be in .gitignore as well:
```
ABOUT-NLS
config.rpath
doc/mdate-sh
m4/
po/stamp-po
```

**Comment by sthibaul** [comment]
Right, addressed them in 3194b87da4d0b84395f436acf20a03345c4da71c

**Comment by rffontenelle** [comment]
Nice, thanks

**Pull request closed without merging**
