### PR TITLE
Fix libspeechd version.h

### PR DESCRIPTION
**Pull request by jpwhiting**
A previous (post 0.11.1) commit removed defining MAJOR_VERSION, etc. from configure.ac. They are still there as macros, but not exported anymore.

This change adds them back and adds making sure they are defined to clibrary.c test so make check will catch it if it happens again somehow.

### CODE REVIEW

**Comment by sthibaul** [comment]
Some version pieces, notably MAJOR_VERSION could be 0 :)
You can simply make the test print them, which will already make sure that they are defined (even if to 0)

**Comment by jpwhiting** [comment]
Yeah, I just noticed that when I ran clibrary test. If I just print them it needs to fail to compile if they aren't defined. Trying, one moment.

**Comment by sthibaul** [comment]
if they aren't defined the code will not compile, that's enough for the test to be effective :)

**Comment by jpwhiting** [comment]
Yep, tested with an #undef in there and compile in make check failed, good. Fixed.

**Pull request merged**
