### PR TITLE
Plug history security hole on the ssip side.

### PR DESCRIPTION
**Pull request by jpwhiting**
Don't allow getting the client list.
Also don't allow getting message list for any client id
other than the current connection's client id.
Updated ssip.texi also.

### CODE REVIEW

**Comment by sthibaul** [comment]
Ok, that looks good (you didn't need to submit another PR, you just need to force-push a new version of your restricthistory branch).

Could you use "git commit --amend" to add "Fixes #335"  so the proper reference to the fixed bug gets recorded in the git log and the bug automatically closed?

Thanks

**Comment by jpwhiting** [comment]
Ack, submitted.

**Comment by sthibaul** [comment]
Mmm, did you really force-push your `restricthistory` branch? I don't see the newer version, https://github.com/jpwhiting/speechd/tree/restricthistory is still showing the old version.

**Comment by jpwhiting** [comment]
My bad, too many remotes. Pushed to an old sheechd-wip by mistake.

**Comment by sthibaul** [comment]
NP, thanks! :)

**Pull request merged**
